package game

type SpeakClasses int8

const (
	_ SpeakClasses = iota
	TALKTYPE_SAY
	TALKTYPE_WHISPER
	TALKTYPE_YELL
	TALKTYPE_PRIVATE_FROM // Received private message
	TALKTYPE_PRIVATE_TO   // Sent private message
	_
	TALKTYPE_CHANNEL_Y
	TALKTYPE_CHANNEL_O
	TALKTYPE_SPELL // Like SAY but with "casts" instead of "says"
	TALKTYPE_PRIVATE_NP
	TALKTYPE_PRIVATE_NP_CONSOLE
	TALKTYPE_PRIVATE_PN
	TALKTYPE_BROADCAST
	TALKTYPE_CHANNEL_R1
	TALKTYPE_PRIVATE_RED_FROM
	TALKTYPE_PRIVATE_RED_TO
	TALKTYPE_MONSTER_SAY  = 36
	TALKTYPE_MONSTER_YELL = 37
	TALKTYPE_POTION       = 52
)
