CREATE TABLE players (
    id bigint auto_increment not null,
    name varchar(50) not null unique,
    account_id bigint not null,
    sex tinyint not null,
    vocation tinyint not null,
    experience bigint not null,
    level smallint not null,
    maglevel smallint not null,
    health smallint not null,
    healthmax smallint not null,
    mana smallint not null,
    manamax smallint not null,
    manaspent bigint not null,
    lookbody smallint not null,
    lookfeet smallint not null,
    lookhead smallint not null,
    looklegs smallint not null,
    looktype smallint not null,
    posx mediumint not null,
    posy mediumint not null,
    posz tinyint not null,
    cap mediumint not null,
    lastlogin datetime,
    lastlogout datetime,
    lastip varchar(15),
    skulltime datetime,
    skull tinyint,
    town_id bigint not null,
    skill_fist int not null,
    skill_fist_tries int not null,
    skill_club int not null,
    skill_club_tries int not null,
    skill_sword int not null,
    skill_sword_tries int not null,
    skill_axe int no
        t null,
    skill_axe_tries int not null,
    skill_dist int not null,
    skill_dist_tries int not null,
    skill_shielding int not null,
    skill_shielding_tries int not null,
    skill_fishing int not null,
    skill_fishing_tries int not null,
    direction tinyint not null,
    primary key(id),
    foreign key(account_id) references account(id),
    foreign key(town_id) references town(id)
);

INSERT INTO players  (name,      account_id, sex, vocation, experience, level, maglevel, health, healthmax, mana, manamax, manaspent, lookbody, lookfeet, lookhead, looklegs, looktype, posx,  posy,     posz, cap, lastlogin,             lastlogout,            lastip,    skulltime,                  skull, town_id, skill_fist, skill_fist_tries, skill_club, skill_club_tries, skill_sword, skill_sword_tries, skill_axe, skill_axe_tries, skill_dist, skill_dist_tries, skill_shielding, skill_shielding_tries, skill_fishing, skill_fishing_tries, direction)
             VALUES ('Goots',    1,          1,   0,        0,          1,     0,        100,    100,       0,    0,       0,         80,       80,       80,       80,       128,      32000, 32000,    7,    100, '2010-01-12 00:00:00', '2010-01-12 00:00:00', '0.0.0.0', '2010-01-12 00:00:00',      0,     1,       10,         100,              10,         100,              10,          100,               10,        100,             10,         100,              10,              100,                   10,            100,                 2),
                    ('GM Goots', 1,          1,   0,        0,          1,     0,        100,    100,       0,    0,       0,         80,       80,       80,       80,       128,      32000, 32000,    7,    100, '2010-01-12 00:00:00', '2010-01-12 00:00:00', '0.0.0.0', '2010-01-12 00:00:00',      0,     1,       10,         100,              10,         100,              10,          100,               10,        100,             10,         100,              10,              100,                   10,            100,                 2);

#SELECT id, name, account_id, sex, vocation, experience, level, maglevel, health, healthmax, mana, manamax, manaspent, lookbody, lookfeet, lookhead, looklegs, looktype, posx, posy, posz, cap, lastlogin, lastlogout, lastip, skulltime, skull, town_id, skill_fist, skill_fist_tries, skill_club, skill_club_tries, skill_sword, skill_sword_tries, skill_axe, skill_axe_tries, skill_dist, skill_dist_tries, skill_shielding, skill_shielding_tries, skill_fishing, skill_fishing_tries, direction FROM players WHERE name = 'Goots'